# Generated by Django 4.1.1 on 2022-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('hours', models.JSONField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
